### ISSUE TITLE
Not working from physical device

### ISSUE THREAD

**Issue by james-lavery** [OYIon/LiveXAML#17]
I've got back to testing this, and am having problems on a physical device.

I'm running Visual Studio for Mac, with a physical Android device. I need a physical device because we're using the built-in barcode scanner in our app.

I've downloaded and installed the latest version of the LiveXAML extension in Visual Studio For Mac.

I've added the LiveXAML package to my PCL project.

My device and computer are on the same WiFi network.

I can see the following in my application output:

> XL: Connecting to the handshake server 169.254.80.80
> XL: Handshake connection timed out
> XL: Registered '/users/jameslavery/documents/p4/thi/musterd/src/dev_jgl2/musterd/app.xaml' as Musterd.App
> XL: Handshake server unreachable 169.254.80.80
> XL: Connecting to the handshake server 10.0.2.2
> XL: Registered '/users/jameslavery/documents/p4/thi/musterd/src/dev_jgl2/musterd/ui/pages/runningcommandpage.xaml' as Musterd.UI.Pages.RunningCommandPage
> XL: Handshake connection failed for 10.0.2.2 One or more errors occurred.
> XL: Handshake server unreachable 10.0.2.2
> XL: Connecting to the handshake server 10.0.3.2
> XL: Handshake connection timed out
> XL: Handshake server unreachable 10.0.3.2
> XL: Failed to find find a handshake server
> XL: Trying to use UDP connection

So it looks like it's managing to connect initially but then timing out. Strange that the server IP address seems to be changing.

**Comment by ionoy** [comment]
Hello James,

There are several localhost pass-thru IP addresses that LiveXAML tries before failing. Different emulators have different environments, that's why LiveXAML tries them all.

It still should work with UDP, even after failing to connect to a server. The device has to be on the same network as the host PC for that to work.

**Comment by ionoy** [comment]
Did you have a chance to test it yet?

**Comment by Dyu13** [comment]
I have the same problem on Visual Studio for Mac. It is working on the Emulator, but not on the device. I tried 2 different devices and 2 different projects (both using FreshMVVM). 

The Mac and the device were on the same network.

**Comment by ionoy** [comment]
There is an ongoing discussion about it on Gitter: https://gitter.im/LiveXAML/Lobby
Do you have "INTERNET" permission enabled?

**Comment by ionoy** [comment]
I've published LiveXAML 1.2.35 which has a new method for the connection with the device. Please try it, and see if it works.

**Comment by ionoy** [comment]
LiveXAML fully supports device debugging now. I can extend your trials if you want to test it.
