### ISSUE TITLE
Changing XAML wipes out visual tree

### ISSUE THREAD

**Issue by kentcb** [OYIon/LiveXAML#19]
I've just managed to get LiveXAML to work today against my netstandard UI project. However, whenever I change the XAML for the current view, there's a small delay before the entire view is "wiped out". This is with extremely simple changes, like modifying a `RowDefinition` height from `5` to `10`. It's like it's trying to refresh the visual tree but is not managing to do so. True on both Android and iOS.

**Comment by kentcb** [comment]
Some more info: I've noticed that not _all_ our views are doing this, but seems to be quite a few.

To understand a bit better what was going on, I ran my app up in iOS and used Reveal to check the visual tree before an after a change.

Here's an example...

Before making a change to the XAML:

![image](https://user-images.githubusercontent.com/1901832/30411400-d77796c0-994f-11e7-9556-33da043ec847.png)

After making a (very simple) change to the XAML:

![image](https://user-images.githubusercontent.com/1901832/30411411-df692592-994f-11e7-9796-37f14e6d83ba.png)

So it seems that part of the visual tree has just gone completely missing...

**Comment by ionoy** [comment]
Do you have any initialization code inside a constructor?

**Comment by kentcb** [comment]
Do you just mean code other than `InitializeComponent`? Because yes I do have some in both cases (when it works and when it doesn't). Is there a log or something I can inspect to see what might be happening?

**Comment by ionoy** [comment]
If there is some code that needs to be called after the construction of the view, you need to create a method that would be called by LiveXAML on every initialization. For example:

```

public MyView()
{
  InitializeComponent();

  MyControl.ItemsSource = ViewModel.Items;
}

===>


public MyView()
{
  InitializeComponent();
  InitializeLiveXaml();
}

// LiveXaml will call any method ending with `LiveXaml` on every update
private InitializeLiveXaml()
{
  MyControl.ItemsSource = ViewModel.Items;
}

```

**Comment by ionoy** [comment]
This feature was added only a few days ago, that's why it's not documented yet. Sorry for that :)

**Comment by kentcb** [comment]
Ah, I see the problem. I'm using ReactiveUI's `WhenActivated` construct, and the page isn't technically deactivating and reactivating when XAML is reloaded. So all the work that I do during activation isn't being re-executed when LiveXAML replaces the visual tree 🤔 

If there was a way to know whether LiveXAML was calling the method versus me calling the method, I could work around it. Not suggesting that's a nice solution though...

Without giving it too much thought, I suspect something like this would be better?

```C#
public MyView()
{
    InitializeComponent();
    InitializeLiveXaml();
}

private void InitializeLiveXaml(bool isReload = false)  // LiveXAML will pass true
{
    this.WhenActivated(DoActivation);

    if (isReload) DoActivation();
}

private void DoActivation()
{
    // actual activation
}
```
But frankly that's a lot of messing around (in every view). It would be better if LiveXAML took care of this transparently (but I'm not sure how).

**Comment by kentcb** [comment]
Ah, here's a much better solution:
```C#
public MyView()
{
    InitializeComponent();

    this.WhenActivated(...);
}

private void InitializeLiveXaml()
{
    var vm = this.ViewModel;
    this.ViewModel = null;
    this.ViewModel = vm;
}
```
Simply re-assigning the VM is generally going to be enough to get any reactive view to respond and re-apply anything it needs to, since activation has already hooked into the VM appropriately.

**Comment by ionoy** [comment]
I think your example can be rewritten as:

```
public MyView()
{
    InitializeComponent();
        
    this.WhenActivated(InitializeLiveXaml);
}

private void InitializeLiveXaml()
{
    //...
}
```

I agree that it seems a bit ugly. There is a possibility to just call the whole constructor on every update, but there are some unsolved problems with that. I'll come back to this problem when I have more time think.

**Comment by ionoy** [comment]
Yes, with reactive bindings it would be enough to replace the value to cause reevaluation. You can also do something like this:

```csharp
public MyView()
{
    InitializeComponent();
        
    this.WhenActivated(InitializeLiveXaml);
}

private void InitializeLiveXaml()
{
    _bindings?.Dispose();
    _bindings = new CompositeDisposable();
    
    this.OneWayBind(...).AddTo(_bindings);
    this.OneWayBind(...).AddTo(_bindings);
}
```

**Comment by kentcb** [comment]
Actually, just realised it's slightly more complicated than this due to the way `WhenAny` works in ReactiveUI. If a property chain is _broken_ it does not tick `null` through the observable sequence. So if I have:
```C#
this
    .WhenAnyValue(x => x.ViewModel.SomeProperty)
    .Do(ArrangeSomeViews)
    .Subscribe();
```
This _isn't_ going to execute in response to the VM being reassigned. And since bindings are built on top of `WhenAny`, they suffer from the same problem.

The reason I thought this was working was because the view I was using happened to use `WhenAnyObservable` to do the bulk of its setup, and that has different semantics.

_ugh_

**Comment by ionoy** [comment]
Is it because the subscription dies of `NullReferenceException` or something else?

**Comment by escamoteur** [comment]
could you come over to RxUI Slack?

**Comment by ionoy** [comment]
Sure
